import Head from "next/head";
import Script from "next/script";
import Topbar from "@/components/topbar";
import Image from "next/image";
import { useState, useEffect } from "react";
import { useTheme } from "next-themes";
import Hero from "@/components/hero";
import Exchange from "@/components/exchange";
import Chart from "@/components/chart";
import Footer from "@/components/footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>Caxo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Topbar />
      <div className="w-full justify-center flex flex-col items-center">
        <Hero />
        <Exchange />
        <Chart />
        <Footer />
      </div>
    </>
  );
}
